---
- hosts: localhost
  vars_files: ./vars.yaml


  tasks:
  - name: Deploy vCenter Server Appliance VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-VCSA' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "{{ vcsa_template_name }}"
      linked_clone: True
      snapshot_src: "{{ vcsa_snapshot_src_name }}"
    delegate_to: localhost

  - name: Change Network Interfaces
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-VCSA' }}"
      label: "Network adapter 1"
      network_name: "{{ student_ID + '-SA-Mgmt' }}"
      state: present
      force: yes
    delegate_to: localhost

  - name: Poweron VCSA VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-VCSA' }}"
      state: "poweredon"
      state_change_timeout: 60
    delegate_to: localhost
